import { Geist } from "next/font/google";
import "./globals.css";
import Header from "../Components/Header/Header.jsx";
import Footer from "@/Components/Footer/Footer";
import ProductContext from "../../context/ProductContext";
import ClothesContext from "../../context/ClothesContext";
import CartContext from "../../context/CartContext";
import FavContext from "../../context/FavContext";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geist = Geist({ subsets: ["latin"] });

export const metadata = {
  title: "Trendiva",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={geist.className}>
        <ClothesContext>
          <ProductContext>
            <CartContext>
              <FavContext>
                <Header />
                {children}
                <Footer />
                <ToastContainer />
              </FavContext>
            </CartContext>
          </ProductContext>
        </ClothesContext>
      </body>
    </html>
  );
}
