import { Geist } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

import Header from "../Components/Header/Header.jsx";
import Footer from "@/Components/Footer/Footer";
import ProductContext from "../../context/ProductContext";
import ClothesContext from "../../context/ClothesContext";
import CartContext from "../../context/CartContext";
import FavContext from "../../context/FavContext";
import { ToastContainer } from "react-toastify";

const geist = Geist({ subsets: ["latin"], preload: true });

export const metadata = {
  title: "Trendiva",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={geist.className}>
        <div className="page-wrapper">
          <ClothesContext>
            <ProductContext>
              <CartContext>
                <FavContext>
                  <Header />
                  <main className="content">{children}</main>
                  <Footer />
                </FavContext>
              </CartContext>
            </ProductContext>
          </ClothesContext>
        </div>
        <ToastContainer />
      </body>
    </html>
  );
}
